---
title: "making_conflicts"
format: 
  html: default
  typst:
    papersize: a4
editor: visual
---

## How to generate merge conflicts

Try to make some of the following edits overlap.

1. Here I started with a new branch `conflicts` where I will create a new document, `main_doc.qmd` with text generated by LittleIpsum (Lorem Ipsum text “tulle latin”).
2. Make a branch on `conflicts` called b1
3. do some edits on `main_doc.qmd` and save and commit. Mark with `b1 edits`.
4. do some more edits on `main_doc.qmd` and save and commit. Mark with `b1 edits`.
5. change back to branch `conflicts` 
6. do some edits on `main_doc.qmd` and save and commit. Mark with `c edits`
7. Create a new branch b2 on `conflicts`.
8. do some more edits on `main_doc.qmd` and save and commit. Mark with `b2 edits`.
9. Change to branch b1. Do some edits on `main_doc.qmd` and save and commit. Mark with `b1 edits v2`.
10. Change to branch `conflicts`. Do some edits on `main_doc.qmd` and save and commit.
11. 9. Change to branch b2. Do some edits on `main_doc.qmd` and save and commit. Mark with `b2 edits v2`.
12. Change to branch `conflicts`. Do some edits on `main_doc.qmd` and save and commit. 
13. Merge branch `b1` into `conflicts`.
14. Do some more edits on `main_doc.qmd` and save and commit. 
15. Merge branch `b2` into `conflicts`.
